name: cppchecks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive .
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
      - run: bazel build //...
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel
      - run: bazel test //...
